# Generated by Django 3.2.13 on 2022-05-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlShort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADS_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('subscribes', models.FloatField()),
                ('coverage', models.FloatField()),
                ('view', models.FloatField()),
                ('cost', models.FloatField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlShort.urlshort')),
            ],
            options={
                'verbose_name': 'ADS_list calculate ',
                'verbose_name_plural': 'ADS_list ',
            },
        ),
    ]
