# Generated by Django 3.2.13 on 2022-05-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlShort', '0003_auto_20220524_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADS_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('vid', models.CharField(max_length=255)),
                ('subscribe', models.IntegerField()),
                ('oxvat', models.FloatField()),
                ('cost', models.FloatField()),
                ('ssilka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urlShort.urlshort')),
            ],
            options={
                'verbose_name': 'ADS_list calculate ',
                'verbose_name_plural': 'ADS_list ',
            },
        ),
    ]
