# Generated by Django 4.0.4 on 2022-04-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role',
            new_name='type',
        ),
    ]
