# Generated by Django 4.0.4 on 2022-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='short_url',
        ),
        migrations.AddField(
            model_name='urlshort',
            name='slug',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
