# Generated by Django 3.2.13 on 2022-05-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlShort', '0002_remove_urlshort_short_url_urlshort_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='director_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auser.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlshort',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
