# Generated by Django 3.2.13 on 2022-05-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import instagram.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('marking', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=instagram.models.slugify_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post of auto post Instagram',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='InstaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Profile',
                'verbose_name_plural': 'Instagram Profiles',
            },
        ),
    ]
