# Generated by Django 3.2.13 on 2022-05-18 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegram.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
                ('link_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hashtag', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=telegram.models.slugify_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post of auto post telegram',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
