# Generated by Django 4.0.3 on 2022-04-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('HISTORY', 'HISTORY'), ('DONE', 'DONE'), ('TESTING', 'TESTING'), ('TO_DO', 'TO_DO'), ('WAITING', 'WAITING'), ('DOING', 'DOING')], default='TO_DO', max_length=20),
        ),
    ]
