# Generated by Django 4.0.4 on 2022-05-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DOING', 'DOING'), ('HISTORY', 'HISTORY'), ('TO_DO', 'TO_DO'), ('WAITING', 'WAITING'), ('DONE', 'DONE'), ('TESTING', 'TESTING')], default='TO_DO', max_length=20),
        ),
    ]
