# Generated by Django 4.0.4 on 2022-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'TO_DO'), ('WAITING', 'WAITING'), ('TESTING', 'TESTING'), ('DOING', 'DOING'), ('DONE', 'DONE'), ('HISTORY', 'HISTORY')], default='TO_DO', max_length=20),
        ),
    ]
