# Generated by Django 3.2.13 on 2022-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DOING', 'DOING'), ('HISTORY', 'HISTORY'), ('TO_DO', 'TO_DO'), ('DONE', 'DONE'), ('TESTING', 'TESTING'), ('WAITING', 'WAITING')], default='TO_DO', max_length=20),
        ),
    ]
