<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-05-17 21:00
=======
# Generated by Django 3.2.12 on 2022-05-12 09:17
>>>>>>> 3990e726691c6a42c09e95c2b149de6d59c3494f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
<<<<<<< HEAD
            field=models.CharField(choices=[('DOING', 'DOING'), ('HISTORY', 'HISTORY'), ('TO_DO', 'TO_DO'), ('DONE', 'DONE'), ('TESTING', 'TESTING'), ('WAITING', 'WAITING')], default='TO_DO', max_length=20),
=======
            field=models.CharField(choices=[('TO_DO', 'TO_DO'), ('HISTORY', 'HISTORY'), ('DOING', 'DOING'), ('DONE', 'DONE'), ('TESTING', 'TESTING'), ('WAITING', 'WAITING')], default='TO_DO', max_length=20),
>>>>>>> 3990e726691c6a42c09e95c2b149de6d59c3494f
        ),
    ]
