# Generated by Django 3.2.13 on 2022-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('TO_DO', 'TO_DO'), ('HISTORY', 'HISTORY'), ('DOING', 'DOING'), ('TESTING', 'TESTING'), ('DONE', 'DONE')], default='TO_DO', max_length=20),
        ),
    ]
