# Generated by Django 3.2.13 on 2022-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DOING', 'DOING'), ('TO_DO', 'TO_DO'), ('TESTING', 'TESTING'), ('WAITING', 'WAITING'), ('DONE', 'DONE'), ('HISTORY', 'HISTORY')], default='TO_DO', max_length=20),
        ),
    ]
