# Generated by Django 3.2.13 on 2022-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('HISTORY', 'HISTORY'), ('WAITING', 'WAITING'), ('DOING', 'DOING'), ('TESTING', 'TESTING'), ('TO_DO', 'TO_DO')], default='TO_DO', max_length=20),
        ),
    ]
